name: buff_lisa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.15+64


environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  cached_network_image:
  camera:
  choice:
  collection:
  connectivity_plus:
  custom_lint:
  drift:
  drift_dev:
  drift_flutter:
  dropdown_search:
  easy_localization:
  exif:
  floating_snackbar:
  flutter:
    sdk: flutter
  flutter_cache_manager:
  flutter_dotenv:
  flutter_login:
  flutter_map:
  flutter_map_geojson:
  flutter_map_location_marker:
  flutter_map_marker_cluster:
  flutter_map_tile_caching:
  flutter_native_splash:
  flutter_riverpod:
  flutter_secure_storage: ^9.2.4
  fluttertoast:
  freezed_annotation:
  geocoding:
  geolocator:
  http:
  image_cropper:
  image_picker:
  in_app_review:
  infinite_scroll_pagination: 4.1.0
  json_annotation: ^4.9.0
  json_serializable:
  latlong2:
  like_button:
  mutex:
  native_exif:
  openapi:
    path: ./api
  path:
  path_provider:
  permission_handler:
  posthog_flutter:
  riverpod_annotation:
  riverpod_generator:
  riverpod_lint:
  select_dialog:
  settings_ui:
  shimmer:
  sliding_up_panel:
  snapping_page_scroll:
  social_media_buttons:
  string_validator:
  transparent_image:
  url_launcher:
  uuid:
  webview_flutter:
  hive_ce:
  hive_ce_flutter:
  shared_preferences:
  firebase_messaging:
  firebase_core:

dev_dependencies:
  build_runner:
  change_app_package_name:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  hive_ce_generator:
  lint:
  meta:
  test:

flutter:
  assets:
    - assets/image/
    - assets/achievements/
    - assets/icon/
    - .env
    - .env.dev
  uses-material-design: true
  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-VariableFont.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "images/pinGui.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/icon/logo.jpg
  android_12:
    image: assets/icon/logoAndroid12.jpg
